### ISSUE TITLE
[Bug]:"saving" on Your Notes  #1

### ISSUE THREAD

**Issue by Sagarkumar7** [Vishesh-Pandey/v-dashboard#14]
despite not writing anything on Your Note it is still showing "saving" symbol continuously.

 
![image](https://github.com/Vishesh-Pandey/v-dashboard/assets/72002419/4dc18e0e-b8bb-4749-8854-efde2ce8a7f6)
![Screenshot 2023-09-27 200918](https://github.com/Vishesh-Pandey/v-dashboard/assets/72002419/addbb278-6dee-4e4a-bbae-58bef662b926)

Steps to see the problem:
1) Go to homepage
2) Click on the your note but dont write anything.

**Comment by Vishesh-Pandey** [comment]
It is to notify the user that anything written here will be saved securely to their v-dashboard account. But as you said this - it might be confusing for other users as well. Hence I will edit the saving alert and make it more understandable. Thank you for your feedback.
